In [4]:
name = input("What is your name? ")
print("Hello " + name)

What is your name? yash
Hello yash


In [5]:
x = 3 == 2
print(x)


False


In [6]:
price = 25
print( not price > 10)

False


In [7]:
temperature = 5
if temperature > 30:
    print("It's a hot day")
    print("Drink plenty of water")
elif temperature > 20:
    print("It's a nice day")
elif temperature > 10:
    print("It's a very nice day")
    print("It's a cold day")
else:
    print("It's cold")
print("Done")

It's cold
Done


In [8]:
birth_year = input("Enter your birth year: ")
age = 2026 - int(birth_year)
print(age)

Enter your birth year: 2006
20


In [9]:
course = 'Python for Beginners'
print('Python' in course)
print(course)


True
Python for Beginners


In [10]:
weight = input("Weight: ")
w = int(weight)
u = w/2.204623
unit = input("(K)g or (L)bs: ")
if unit == "K":
     print("Weight in Kg: ", w)
elif unit == "l":
     print("Weight in Kg: ", u )
else:
    print("-1")



Weight: 66
(K)g or (L)bs: K
Weight in Kg:  66


In [11]:
i = 1
while i <= 10:
    print((2*i -1 ) * "*")
    i = i+1

*
***
*****
*******
*********
***********
*************
***************
*****************
*******************


In [12]:
names = ["yash", "chirayu", "jefferson"]
names[0] = "adi"
print(names[0:3])

['adi', 'chirayu', 'jefferson']


In [13]:
def square(x):
    return x * x

print(square(5))
print(square(10))

25
100


In [14]:
student = {
    "name": "Yash",
    "age": 18,
    "branch": "Chemical"
}

print(student["name"])
print(student["branch"])

Yash
Chemical


In [15]:
class Student:
    def __init__(self, name):
        self.name = name

    def greet(self):
        print("Hello,", self.name)

s1 = Student("Yash")
s1.greet()

Hello, Yash


In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(arr * 2)
print(arr + 10)

[1 2 3 4 5]
[ 2  4  6  8 10]
[11 12 13 14 15]
