In [1]:
import torch

print(torch.__version__)


2.11.0+cpu


# Creating tensors

In [2]:


a = torch.tensor([1, 2, 3])
b = torch.tensor([[1, 2], [3, 4]])

print(a)
print(b)

tensor([1, 2, 3])
tensor([[1, 2],
        [3, 4]])


# Different ways to create tensors

In [3]:


zeros = torch.zeros(3, 3)
ones = torch.ones(2, 4)
random = torch.rand(2, 3)

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Random:\n", random)

Zeros:
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
Ones:
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
Random:
 tensor([[0.8067, 0.7959, 0.8132],
        [0.2511, 0.0850, 0.6021]])


## Tensor Properties

In [4]:
x = torch.rand(3, 4)

print("Shape:", x.shape)
print("Size:", x.size())
print("Data Type:", x.dtype)
print("Device:", x.device)

Shape: torch.Size([3, 4])
Size: torch.Size([3, 4])
Data Type: torch.float32
Device: cpu


## Tensor Operations

In [5]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

print("Addition:", x + y)
print("Subtraction:", x - y)
print("Multiplication:", x * y)
print("Division:", x / y)

Addition: tensor([5, 7, 9])
Subtraction: tensor([-3, -3, -3])
Multiplication: tensor([ 4, 10, 18])
Division: tensor([0.2500, 0.4000, 0.5000])


In [6]:
print(torch.add(x, y))
print(torch.mul(x, y))

tensor([5, 7, 9])
tensor([ 4, 10, 18])


## Matrix Operations

In [7]:

A = torch.tensor([[1., 2.],
                  [3., 4.]])

B = torch.tensor([[5., 6.],
                  [7., 8.]])

print(torch.matmul(A, B))

tensor([[19., 22.],
        [43., 50.]])


## Reshaping Tensors

In [8]:
x = torch.arange(12)

print(x)

reshaped = x.reshape(3, 4)

print(reshaped)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [9]:
flattened = reshaped.flatten()

print(flattened)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


## Indexing and Slicing

In [10]:
x = torch.tensor([[10,20,30],
                  [40,50,60]])

print(x[0])
print(x[:,1])
print(x[1,2])

tensor([10, 20, 30])
tensor([20, 50])
tensor(60)


## NumPy and PyTorch

In [11]:
import numpy as np

array = np.array([1,2,3])

tensor = torch.from_numpy(array)

print(tensor)

tensor([1, 2, 3])


In [12]:
back_to_numpy = tensor.numpy()

print(back_to_numpy)

[1 2 3]


## Autograd

In [14]:
import torch

x = torch.tensor(2.0, requires_grad=True)

print(x)

tensor(2., requires_grad=True)


In [15]:
y = x**2 + 3*x + 1

print(y)

tensor(11., grad_fn=<AddBackward0>)


In [16]:
y.backward()

print(x.grad)

tensor(7.)


In [17]:
a = torch.tensor([2.0,3.0], requires_grad=True)

b = a * 2

c = b.mean()

c.backward()

print(a.grad)

tensor([1., 1.])


## Building a Simple Neural Network

In [19]:
import torch.nn as nn

In [21]:
model = nn.Sequential(
    nn.Linear(2,4),
    nn.ReLU(),
    nn.Linear(4,1)
)

print(model)

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): ReLU()
  (2): Linear(in_features=4, out_features=1, bias=True)
)


In [22]:
sample = torch.tensor([[2.0,3.0]])

output = model(sample)

print(output)

tensor([[1.3159]], grad_fn=<AddmmBackward0>)


## Loss Functions

In [24]:
criterion = nn.MSELoss()

prediction = torch.tensor([2.5])

target = torch.tensor([3.0])

loss = criterion(prediction,target)

print(loss)

tensor(0.2500)


In [25]:
criterion = nn.CrossEntropyLoss()

prediction = torch.tensor([[0.1,2.0,0.3]])

target = torch.tensor([1])

loss = criterion(prediction,target)

print(loss)

tensor(0.2869)


## Optimizers

In [27]:
import torch.optim as optim

optimizer = optim.SGD(
    model.parameters(),
    lr=0.01
)

print(optimizer)

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 0.01
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)


In [28]:
adam = optim.Adam(
    model.parameters(),
    lr=0.001
)

print(adam)

Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    decoupled_weight_decay: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.001
    maximize: False
    weight_decay: 0
)


## Training Loop

In [30]:
criterion = nn.MSELoss()

optimizer = optim.SGD(model.parameters(),lr=0.01)

In [31]:
inputs = torch.tensor([[1.0,2.0]])

targets = torch.tensor([[1.0]])

In [32]:
for epoch in range(10):

    optimizer.zero_grad()

    outputs = model(inputs)

    loss = criterion(outputs,targets)

    loss.backward()

    optimizer.step()

    print(f"Epoch {epoch+1}: Loss = {loss.item():.4f}")

Epoch 1: Loss = 0.0134
Epoch 2: Loss = 0.0115
Epoch 3: Loss = 0.0099
Epoch 4: Loss = 0.0085
Epoch 5: Loss = 0.0072
Epoch 6: Loss = 0.0062
Epoch 7: Loss = 0.0053
Epoch 8: Loss = 0.0045
Epoch 9: Loss = 0.0039
Epoch 10: Loss = 0.0033


## Saving and Loading Models

In [34]:
torch.save(model.state_dict(),"model.pth")

In [35]:
new_model = nn.Sequential(
    nn.Linear(2,4),
    nn.ReLU(),
    nn.Linear(4,1)
)

new_model.load_state_dict(torch.load("model.pth"))

new_model.eval()

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): ReLU()
  (2): Linear(in_features=4, out_features=1, bias=True)
)

## GPU Support

In [37]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print(device)

cpu


In [38]:
model.to(device)

inputs = inputs.to(device)

outputs = model(inputs)

print(outputs)

tensor([[0.9469]], grad_fn=<AddmmBackward0>)
