In [1]:
import tensorflow as tf

print(tf.__version__)

2.20.0


## Creating Tensors

In [4]:
a = tf.constant([1,2,3])

print(a)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [5]:
b = tf.constant([[1,2],[3,4]])

print(b)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


## Tensor Properties

In [7]:
print("Shape :", b.shape)
print("Data Type :", b.dtype)

Shape : (2, 2)
Data Type : <dtype: 'int32'>


## Variables

In [9]:
v = tf.Variable([1.0,2.0,3.0])

print(v)

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>


## Mathematical Operations

In [11]:
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])

print(x+y)
print(x-y)
print(x*y)
print(x/y)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [12]:
A = tf.constant([[1.,2.],[3.,4.]])
B = tf.constant([[5.,6.],[7.,8.]])

print(tf.matmul(A,B))

tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)


## Reshaping Tensors

In [14]:
x = tf.range(12)

print(x)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11], shape=(12,), dtype=int32)


In [15]:
reshaped = tf.reshape(x,(3,4))

print(reshaped)

tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]], shape=(3, 4), dtype=int32)


## Sequential Model

In [17]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [18]:
model = Sequential([
    Dense(8,activation="relu"),
    Dense(4,activation="relu"),
    Dense(1)
])

model.build((None,2))

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 8)              │            24 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 4)              │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 65 (260.00 B)

 Trainable params: 65 (260.00 B)

 Non-trainable params: 0 (0.00 B)

## Compile Model

In [19]:
import numpy as np

X = np.array([
    [1,2],
    [2,3],
    [3,4],
    [4,5],
    [5,6]
],dtype=float)

Y = np.array([
    [2],
    [3],
    [4],
    [5],
    [6]
],dtype=float)

## Train Model

In [27]:
model.compile(
    optimizer='adam',
    loss='mean_squared_error',
    metrics=['mae']
)

history = model.fit(
    X,
    Y,
    epochs=50,
    verbose=1
)

Epoch 1/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 13.5834 - mae: 3.4680
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 13.4919 - mae: 3.4563
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - loss: 13.4004 - mae: 3.4445
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 13.3087 - mae: 3.4326
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 13.2170 - mae: 3.4207
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 13.1251 - mae: 3.4088
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - loss: 13.0332 - mae: 3.3967
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - loss: 12.9412 - mae: 3.3847
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - loss: 12.8492 - mae: 3.3726
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - loss: 12.7570 - mae: 3.3604
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - loss: 12.6648 - mae: 3.3482
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 12.5726 - mae: 3.3359
Epoch 13/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/st

In [22]:
history = model.fit(
    X,
    Y,
    epochs=50,
    verbose=1
)

Epoch 1/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 18.1240
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - loss: 18.0333
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - loss: 17.9433
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step - loss: 17.8533
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - loss: 17.7634
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - loss: 17.6744
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - loss: 17.5856
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 17.4972
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 17.4097
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 17.3222
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 17.2345
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step - loss: 17.1467
Epoch 13/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - loss: 17.0589
Epoch 14/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 16.9709
Epoch 15/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - loss: 16.8828
Epoch 16/50
1/

## Prediction

In [23]:
prediction = model.predict(np.array([[6,7]],dtype=float))

print(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step
[[0.8856585]]


## Evaluate Model

In [25]:
loss_value = model.evaluate(
    X,
    Y,
    verbose=0
)

print("Loss :",loss_value)
print("MAE was not available because it was not specified in model.compile().")
print("To get MAE, please add metrics=['mae'] to the model.compile() method in cell 'myMGrc9xn9Pm' and re-run the compilation and evaluation steps.")

Loss : 13.583395004272461
MAE was not available because it was not specified in model.compile().
To get MAE, please add metrics=['mae'] to the model.compile() method in cell 'myMGrc9xn9Pm' and re-run the compilation and evaluation steps.


In [28]:
loss, mae = model.evaluate(
    X,
    Y,
    verbose=0
)

print("Loss :",loss)
print("MAE :",mae)

Loss : 8.958971977233887
MAE : 2.8139169216156006


## Save Model

In [29]:
model.save("tensorflow_model.keras")

## Load Model

In [30]:
loaded_model = tf.keras.models.load_model("tensorflow_model.keras")

loaded_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 8)              │            24 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 4)              │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 197 (792.00 B)

 Trainable params: 65 (260.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 132 (532.00 B)

## GPU Availability

In [31]:
## GPU Availability